### ISSUE TITLE
Back Navigation Key Not working in YouTube application.

### ISSUE THREAD

**Issue by andigenn** [Arafatulislamantor/YouTubeReVanced#6]
Back Navigation Key Not working in YouTube application.

Device: Xiaomi Mi 8
Installed version: youtube_revanced_17.49.37
Frequency of issue: always
MIUI: 12.0.3
Android 10

**Comment by Arafatulislamantor** [comment]
Yes...back key not Work from yt home screen...it's maybe ReVanced feature...you can use home button or recentbutton directly..it's also happened to me...

**Comment by Arafatulislamantor** [comment]
> Back Navigation Key Not working in YouTube application.
> 
> Device: Xiaomi Mi 8 Installed version: youtube_revanced_17.49.37 Frequency of issue: always MIUI: 12.0.3 Android 10

Yes...back key not Work from yt home screen...it's maybe ReVanced feature...you can use home button or recentbutton directly..it's also happened to me..

**Comment by andigenn** [comment]
Ok, thanks.
